### ISSUE TITLE
The interface output is garbled

### ISSUE THREAD

**Issue by wlisboy** [XGilmar/JetBrains-reset-trial#12]
![Snipaste_2024-11-07_11-01-53](https://github.com/user-attachments/assets/d86d3d19-9356-4298-8a07-d217bb423a2e)

**Comment by XGilmar** [comment]
> ![Snipaste_2024-11-07_11-01-53](https://private-user-images.githubusercontent.com/97881664/383826671-d86d3d19-9356-4298-8a07-d217bb423a2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTgwNjAsIm5iZiI6MTczMDk1Nzc2MCwicGF0aCI6Ii85Nzg4MTY2NC8zODM4MjY2NzEtZDg2ZDNkMTktOTM1Ni00Mjk4LThhMDctZDIxN2JiNDIzYTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA1MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZDdjN2M1YzVjYjk0ZTJiOTA5ZmI1YTUzNjg3YjRkYWJhNWIzNjJiM2M1MTBjNWViNWZkMGRkNjEwNmFiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.unGtVourLzLW4zZ2VTy3p7X1lyVAq0r1f6FLIV4_iOU)

It is normal that it presents small distortions, remember that it is a demo. Each time a new update will be made. My question is if I restore the license?

**Comment by wlisboy** [comment]
The trial is normal, just like when it was newly installed, with a trial option
