### ISSUE TITLE
Not working on Pycharm 2024.1.4

### ISSUE THREAD

**Issue by AMHZR** [XGilmar/JetBrains-reset-trial#6]
trying to use it over my Pycharm 2024.1.4, seems the magic wand has no impact on it.. 

![Screenshot 2024-07-30 at 12 32 27 PM](https://github.com/user-attachments/assets/60dcebec-491f-41d3-a6ee-2e92c76105dc)

**Comment by XGilmar** [comment]
> trying to use it over my Pycharm 2024.1.4, seems the magic wand has no impact on it..
> 


This will take a little more time, as I don't have a mac to fully review what is going on.

**Comment by DanielOberlechner** [comment]
@XGilmar 
Today I tried to reset my pycharm and it seems like it doesnt work anymore.
Some time ago it worked flawless but now it deletes the files without problem but I cant activate the trial even when I click the available "start trial" button.

I get:
The trial period has ended. To continue using PyCharm 2024.1, purchase a subscription.

Maybe jetbrains has fixed this workaround by now?

**Comment by DanielOberlechner** [comment]
> I'm on mac intel + IntelijIdea and I do:
> 
> 1. Uninstall app by drag-n-drop app from apps folder to trash
> 2. Remove all folders except latest(`IntelliJIdea2024.2` in my case) in `open ~/Library/Application\ Support/JetBrains/`
>    
>    * so the folder contains only one IntelliJIdea2024.2 folder
>    * `consentOptions` is removed
>    * `~/Library/Application\ Support/JetBrains/IntelliJIdea2024.2/options/other.xml` is removed
>    * `app-internal-state.db`, `idea.key` too
> 3. Remove plists:
>    
>    * `rm -rf ~/Library/Preferences/com.jetbrains.datagrip.plist`
>    * `rm -rf ~/Library/Preferences/com.jetbrains.intellij.plist`
>    * `rm ~/Library/Preferences/com.apple.java.util.prefs.plist`
> 4. Download latest IntelliJIdea2024.2 from their site (`IntelliJ IDEA 2024.2.3 (Ultimate Edition)` in my case)
> 5. Install it
> 6. Now it asks to accept rules and allows trial

Your steps are not necessary to delete and download again. In my opinion it would be too much of a effort to do this every month.

You can simply try this script it works.
https://gist.githubusercontent.com/patchthecode/6eeeea214540bb735bd54548ead4b85f/raw/38e9cd6feb8dc7f43967058740a8b6ac83c7c796/reset_idea_trial.sh

I'm gonna adapt the software to work again on macOS. It's probably gonna take a few days I think.

**Comment by DanielOberlechner** [comment]
Issue fixed!

**Comment by DanielOberlechner** [comment]
the issue is already fixed, the software is up2date ...
